# Generated by Django 5.1.1 on 2024-10-03 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boughtitem',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='solditem',
            name='buyer_id',
        ),
        migrations.AddField(
            model_name='boughtitem',
            name='seller_pid',
            field=models.CharField(default='UNKNOWN', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solditem',
            name='buyer_pid',
            field=models.CharField(default='UNKNOWN', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boughtitem',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_items', to='store.userprofile'),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='store.userprofile'),
        ),
    ]
